/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.Color;
import java.util.Properties;
import javax.swing.UIManager;
import utility.IOUtils;

/**
 *
 * @author Hoang
 */
public class LoginFrame extends javax.swing.JFrame {

    public static LoginConfig config;

    /**
     * Creates new form TestFrame
     */
    public LoginFrame() {
        // Thiet lap GUI
        initComponents();
        setBackground(new Color(0, 255, 0, 0));
        pnContent.setBackground(new Color(0, 255, 0, 0));
        pnContent.add(new LoginPanel(pnContent));
        pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Login System");
        setMinimumSize(new java.awt.Dimension(269, 554));
        setUndecorated(true);
        setResizable(false);

        pnContent.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Load config tu file len, neu file khong ton tai thi tao moi
                try {
                    config = (LoginConfig) IOUtils.readObject(getClass().getResource("config").getPath());
                } catch (Exception e) {
                    // neu bi loi doc file thi config van la null
                }

                if (config == null) { // Neu file config khong ton tai
                    config = new LoginConfig(LoginConfig.HOST, LoginConfig.PORT, LoginConfig.DBNAME, LoginConfig.NAME, LoginConfig.PASSWORD, LoginConfig.USER_NAME, LoginConfig.USER_PASSWORD);

                    LoginFrame loginFrame = new LoginFrame();
                    loginFrame.setVisible(true);
                } else { // Neu file config da ton tai
//                    System.out.println("config trong LoginFrame" + config.toString());

                    try {
                        Properties props = new Properties();
                        props.put("logoString", "");
                        props.put("macStyleWindowDecoration", "off");
                        HiFiLookAndFeel laf = new HiFiLookAndFeel();
                        laf.setTheme(props);
                        UIManager.setLookAndFeel(laf);
                        MainFrame mainFrame = new MainFrame();
                        mainFrame.setVisible(true);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnContent;
    // End of variables declaration//GEN-END:variables
}
