/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.Color;
import java.util.Properties;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import org.jdesktop.xswingx.PromptSupport;
import utility.DBUtils;
import utility.IOUtils;
import utility.SwingUtils;

/**
 *
 * @author Hoang
 */
public class LoginPanel extends javax.swing.JPanel {

    private LoginFrame loginFrame;
    private JPanel parent;
    private LoginConfig config;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(JPanel parent) {
        this.parent = parent;
        this.loginFrame = (LoginFrame) parent.getParent().getParent().getParent().getParent();
        this.config = LoginFrame.config;

        // Set thuoc tinh cho GUI
        initComponents();
        setBackground(new Color(0, 255, 0, 0));
        tfUserName.setBackground(new Color(255, 255, 255, 150));
        tfUserName.setHorizontalAlignment(JTextField.CENTER);
        tfPassword.setBackground(new Color(255, 255, 255, 150));
        tfPassword.setHorizontalAlignment(JTextField.CENTER);

        //Set place holder
        PromptSupport.setForeground(Color.RED, tfUserName);
        PromptSupport.setForeground(Color.RED, tfPassword);
        PromptSupport.setPrompt("Login name...", tfUserName);
        PromptSupport.setPrompt("Login password...", tfPassword);

        // Khoi tao tri mac dinh
        tfUserName.setText(config.userName);
        tfPassword.setText(config.userPassword);
        
        // Set focus luc khoi tao
        tfUserName.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUserName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btOK = new javax.swing.JButton();
        btConnect = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        lbBg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(270, 554));
        setLayout(null);

        tfUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserNameFocusLost(evt);
            }
        });
        tfUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserNameActionPerformed(evt);
            }
        });
        add(tfUserName);
        tfUserName.setBounds(60, 120, 150, 40);

        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        add(tfPassword);
        tfPassword.setBounds(60, 170, 150, 40);

        btOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main/OK.png"))); // NOI18N
        btOK.setBorderPainted(false);
        btOK.setContentAreaFilled(false);
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });
        add(btOK);
        btOK.setBounds(30, 420, 50, 50);

        btConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main/Connect.png"))); // NOI18N
        btConnect.setBorderPainted(false);
        btConnect.setContentAreaFilled(false);
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnectActionPerformed(evt);
            }
        });
        add(btConnect);
        btConnect.setBounds(110, 420, 50, 50);

        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main/Cancel.png"))); // NOI18N
        btCancel.setBorderPainted(false);
        btCancel.setContentAreaFilled(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        add(btCancel);
        btCancel.setBounds(190, 420, 50, 50);

        lbBg.setBackground(new java.awt.Color(255, 255, 255));
        lbBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/main/Login.png"))); // NOI18N
        add(lbBg);
        lbBg.setBounds(0, 0, 269, 554);
    }// </editor-fold>//GEN-END:initComponents

    private void tfUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusGained
        tfUserName.setBackground(new Color(255, 255, 255, 255));
        tfUserName.selectAll();
    }//GEN-LAST:event_tfUserNameFocusGained

    private void tfUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusLost
        tfUserName.setBackground(new Color(255, 255, 255, 150));
    }//GEN-LAST:event_tfUserNameFocusLost

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        tfPassword.setBackground(new Color(255, 255, 255, 255));
        tfPassword.selectAll();
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        tfPassword.setBackground(new Color(255, 255, 255, 150));
    }//GEN-LAST:event_tfPasswordFocusLost

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        exit();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnectActionPerformed
        config.userName = tfUserName.getText();
        config.userPassword = new String(tfPassword.getPassword());
        reloadContentPanel();
    }//GEN-LAST:event_btConnectActionPerformed

    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        login();
    }//GEN-LAST:event_btOKActionPerformed

    private void tfUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserNameActionPerformed
        login();
    }//GEN-LAST:event_tfUserNameActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        login();
    }//GEN-LAST:event_tfPasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btConnect;
    private javax.swing.JButton btOK;
    private javax.swing.JLabel lbBg;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables

    private void login() {
        // Neu username va password dung thi ghi data xuong file roi chuyen sang main frame
        if (checkLogin()) {
            // Ghi du lieu dang nhap vao file
            config.userName = tfUserName.getText();
            config.userPassword = new String(tfPassword.getPassword());
            IOUtils.writeObject(getClass().getResource("config").getPath(), config);

            // Chuyen sang main frame
            try {
                Properties props = new Properties();
                props.put("logoString", "");
                props.put("macStyleWindowDecoration", "off");
                HiFiLookAndFeel laf = new HiFiLookAndFeel();
                laf.setTheme(props);
                UIManager.setLookAndFeel(laf);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            new MainFrame().setVisible(true);

            // Dong login frame
            loginFrame.dispose();
        } else {
            SwingUtils.showErrorDialog("Username or password not correct!");
            tfUserName.requestFocus();
        }
    }

    private void exit() {
        if (SwingUtils.showConfirmDialog("Are you sure to quit?") == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private boolean checkLogin() {
        // Moc database len check

        return true;
    }

    private void reloadContentPanel() {
        parent.removeAll();
        parent.add(new ConfigPanel(parent));
        parent.validate();
        parent.repaint();
    }
}
