/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer.controller;

import customer.model.CustomerLevel;
import customer.model.CustomerLevelTableModel;
import database.DBProvider;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.util.Arrays;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JButton;
import javax.swing.event.ListSelectionEvent;
import utility.SwingUtils;

/**
 *
 * @author Hoang
 */
public class CustomerLevelDialog extends javax.swing.JDialog {

    private CustomerLevelTableModel customerLevelTableModel;
    // Text cua button thay doi khi update du lieu
    private String buttonText;

    // Flag de biet insert, update action da finish chua
    private boolean isFinished;

    // Customer level dang duoc chon trong table
    private CustomerLevel selectedCustomerLevel;

    /**
     * Creates new form CustomerDialog
     */
    public CustomerLevelDialog() {
        initComponents();
        setLocationRelativeTo(null);
        setButtonEnabled(false, btRefresh, btCancel);

        // Selecting customer level in the table
        selectedCustomerLevel = new CustomerLevel();

        // Set data cho table
        customerLevelTableModel = new CustomerLevelTableModel();
        tbLevelList.setModel(customerLevelTableModel);

        // Bat su kien select row tren table
        tbLevelList.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            DefaultListSelectionModel model = (DefaultListSelectionModel) e.getSource();
            if (!model.isSelectionEmpty()) {
                fetchCustomerLevelDetails();
                setButtonEnabled(true);
            } else {
//                resetCustomerLevelDetails();
                setButtonEnabled(false, btRefresh, btCancel);
            }
        });

        // Set height cho table header
        tbLevelList.getTableHeader().setPreferredSize(new Dimension(100, 30));
    }

    private void fetchCustomerLevelDetails() {
        int selectedRow = tbLevelList.getSelectedRow();

        selectedCustomerLevel.setCusLevelID((int) tbLevelList.getValueAt(selectedRow, 0));
        selectedCustomerLevel.setCusLevel((int) tbLevelList.getValueAt(selectedRow, 1));
        selectedCustomerLevel.setCusLevelName((String) tbLevelList.getValueAt(selectedRow, 2));
        selectedCustomerLevel.setCusDiscount((float) tbLevelList.getValueAt(selectedRow, 3) / 100);

//        spLevel.setValue(selectedCustomerLevel.getCusLevel());
//        tfLevelName.setText(selectedCustomerLevel.getCusLevelName());
//        spDiscount.setValue(selectedCustomerLevel.getCusDiscount() * 100);
    }

//    private void resetCustomerLevelDetails() {
//        spLevel.setValue(0);
//        tfLevelName.setText(null);
//        spDiscount.setValue(0);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbLevelList = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Level Management");
        setMinimumSize(null);
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(560, 400));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Level List"));

        tbLevelList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Level", "Name", "Discount (%)"
            }
        ));
        tbLevelList.setFillsViewportHeight(true);
        tbLevelList.setPreferredSize(new java.awt.Dimension(560, 80));
        tbLevelList.setRowHeight(20);
        tbLevelList.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbLevelList);

        btAdd.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/Add3.png"))); // NOI18N
        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDelete.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/Delete2.png"))); // NOI18N
        btDelete.setText("Remove");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        btRefresh.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/Refresh2.png"))); // NOI18N
        btRefresh.setText("Refresh");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });

        btCancel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order/Cancel2.png"))); // NOI18N
        btCancel.setText("Close");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        insertAction();
    }//GEN-LAST:event_btAddActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        deleteAction();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        refreshAction();
    }//GEN-LAST:event_btRefreshActionPerformed

    private void refreshAction() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        tbLevelList.getSelectionModel().clearSelection();
        customerLevelTableModel = new CustomerLevelTableModel();
        setCursor(null);
        SwingUtils.showInfoDialog(DBProvider.DB_REFRESH);
    }

    private void insertAction() {
        if (!isFinished) {
            setUpdatable(true, btAdd);
//            resetCustomerLevelDetails();
//            spLevel.requestFocus();
            isFinished = true;
        } else {
            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            setUpdatable(false, btAdd);
            
            CustomerLevel customerLevel = new CustomerLevel();
//            customerLevel.setCusLevel((int) spLevel.getValue());
//            customerLevel.setCusLevelName(tfLevelName.getText());
//            // Convert from int to float
//            int tmp = (int) spDiscount.getValue();
//            float discount = (float) tmp / 100;
//            customerLevel.setCusDiscount(discount);
            
            customerLevelTableModel.insert(customerLevel);
            isFinished = false;
            setCursor(null);
        }
    }

    private void updateAction() {
//        if (!isFinished) {
//            setUpdatable(true, btUpdate);
//            spLevel.requestFocus();
//            isFinished = true;
//        } else {
//            setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
//            setUpdatable(false, btUpdate);
//            selectedCustomerLevel.setCusLevel((int) spLevel.getValue());
//            selectedCustomerLevel.setCusLevelName(tfLevelName.getText());
//            // Convert from int to float
//            int tmp = (int) spDiscount.getValue();
//            float discount = (float) tmp / 100;
//            selectedCustomerLevel.setCusDiscount(discount);
//            customerLevelTableModel.update(selectedCustomerLevel);
//            isFinished = false;
//            setCursor(null);
//        }
    }

    private void deleteAction() {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        customerLevelTableModel.delete(selectedCustomerLevel);
        tbLevelList.getSelectionModel().clearSelection();
        setCursor(null);
    }

    private void setUpdatable(boolean updatable, JButton... exclude) {
        // Set enable cho vung nhap lieu
//        spLevel.setEnabled(updatable);
//        tfLevelName.setEnabled(updatable);
//        spDiscount.setEnabled(updatable);

        // Set disable cho may button update
        setButtonEnabled(!updatable, exclude);

        // Chinh giao dien cho may button excluded
        if (exclude.length != 0) {
            exclude[0].setEnabled(true);
            if (updatable) {
                // Doi font color mau do khi dang update
                exclude[0].setForeground(Color.RED);
                buttonText = exclude[0].getText();
                exclude[0].setText("Save");
            } else {
                // Doi font color ve mac dinh khi update xong
                exclude[0].setForeground(null);
                exclude[0].setText(buttonText);
            }
        }
    }

    private void setButtonEnabled(boolean enabled, JButton... exclude) {
        btRefresh.setEnabled(enabled);
        btDelete.setEnabled(enabled);
//        btUpdate.setEnabled(enabled);
        btAdd.setEnabled(enabled);
        btCancel.setEnabled(enabled);

        // Ngoai tru may button nay luon luon enable
        if (exclude.length != 0) {
            Arrays.stream(exclude).forEach(b -> b.setEnabled(true));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLevelList;
    // End of variables declaration//GEN-END:variables
}
